arquivo 16
Um erro novamente diante arquivo 15 consertei causo um outro erro:/App.js: Identifier 'QUIZ' has already been declared. (164:6)
  162 | // =========================================
  163 |
> 164 | const QUIZ = [
      |       ^
  165 |   // Módulo 1
  166 |   { id: "m1q1", module: "m1", question: "O que é conta corrente?", options: ["Conta para movimentações", "Investimento"], answer: 0 },
  167 |   { id: "m1q2", module: "m1", question: "O que é cartão débito?", options: ["Paga na hora", "Paga depois"], answer: 0 },
  Evaluating App.js
  Loading App.js
Error: /module:/App.js: Identifier 'QUIZ' has already been declared. (164:6)
  162 | // =========================================
  163 |
> 164 | const QUIZ = [
      |       ^
  165 |   // Módulo 1
  166 |   { id: "m1q1", module: "m1", question: "O que é conta corrente?", options: ["Conta para movimentações", "Investimento"], answer: 0 },
  167 |   { id: "m1q2", module: "m1", question: "O que é cartão débito?", options: ["Paga na hora", "Paga depois"], answer: 0 },
    at Object.eval (.pp.js:1:113)
    at eval (.pp.js:2:4)
    at eval (.pp.js:3:3)
    at eval (<anonymous>)